swagger: "2.0"
info:
  version: "0.0.1"
  title: CSV to GEOJSON API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /convert:
    # binds a127 app logic to a route
    x-swagger-router-controller: convert
    get:
      description: CSVをgeojsonに変換する
      # used as the method name of the controller
      operationId: convert
      parameters:
        - name: url
          in: query
          description: CSVファイルのURL
          required: true
          type: string
        - name: latfield
          in: query
          description: CSV中の緯度のヘッダ名
          required: true
          type: string
        - name: lngfield
          in: query
          description: CSV中の経度のヘッダ名
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: object
            items:
              # a pointer to a definition
              $ref: "#/definitions/ConvertResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  "/convert/github/push/{repo}":
    # binds a127 app logic to a route
    x-swagger-router-controller: convert
    put:
      description: CSVをgeojsonに変換してgithubにpushする
      # used as the method name of the controller
      operationId: githubPush
      parameters:
        - name: repo
          in: path
          description: リポジトリ名
          required: true
          type: string
        - name: branch
          in: formData
          description: ブランチ名(省略時はdefalut branch)
          required: false
          type: string
        - name: url
          in: formData
          description: CSVファイルのURL
          required: true
          type: string
        - name: latfield
          in: formData
          description: CSV中の緯度のヘッダ名
          required: true
          type: string
        - name: lngfield
          in: formData
          description: CSV中の経度のヘッダ名
          required: true
          type: string
        - name: name
          in: formData
          description: geojsonファイル名
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: object
            items:
              # a pointer to a definition
              $ref: "#/definitions/ConvertResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /github:
    # binds a127 app logic to a route
    x-swagger-router-controller: github
    get:
      description: GitHub APIのテスト用
      # used as the method name of the controller
      operationId: github
      parameters:
        - name: url
          in: query
          description: dummy
          required: true
          type: string
        #- name: url
        #  in: formData
        #  description: CSVファイルのURL
        #  required: true
        #  type: string
        #- name: latfield
        #  in: formData
        #  description: CSV中の緯度のヘッダ名
        #  required: true
        #  type: string
        #- name: lngfield
        #  in: formData
        #  description: CSV中の経度のヘッダ名
        #  required: true
        #  type: string
      responses:
        "200":
          description: Success
          schema:
            type: object
            items:
              # a pointer to a definition
              $ref: "#/definitions/GitHubResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  "/github/push/{username}/{usertype}":
    # binds a127 app logic to a route
    # controller/ に置くJS名を指定する
    x-swagger-router-controller: github
    get:
      description: Path階層化のテスト
      # used as the method name of the controller
      # module.exportsで定義するメソッドのキーを指定する
      operationId: githubPush
      parameters:
        - name: username
          in: path
          description: dummy
          required: true
          type: string
        - name: usertype
          in: path
          description: dummy
          required: true
          type: string
        - name: name
          in: query
          description: dummy
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: object
            items:
              # a pointer to a definition
              $ref: "#/definitions/GitHubPushResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  ConvertResponse:
    required:
      - url
      - latfield
      - lngfield
    properties:
      url:
        type: string
      latfield:
        type: string
      lngfield:
        type: string
  GitHubResponse:
    required:
      - url
    #  - latfield
    #  - lngfield
    properties:
      url:
        type: string
    #  latfield:
    #    type: string
    #  lngfield:
    #    type: string
  GitHubPushResponse:
    type: object
    properties:
      username:
        type: string
      usertype:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
